"""add order table

Revision ID: 748dbf1a7ee2
Revises: 536366596e20
Create Date: 2024-04-25 20:29:34.306659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748dbf1a7ee2'
down_revision: Union[str, None] = '536366596e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=50), nullable=True),
    sa.Column('order_text', sa.Text(), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_status'), 'order', ['order_status'], unique=False)
    op.create_index(op.f('ix_order_order_type'), 'order', ['order_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_type'), table_name='order')
    op.drop_index(op.f('ix_order_order_status'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
